# Bash customizations.
# $HOME/.bashrc is a symbolic-link to this file.

set -o vi

# Speed things up a little.
export LC_ALL=C
export LANG=C

# Show the 20 most "recently-downloaded" files in the given directory.
recdld() {
  LS_DIR=${1-$PWD}
  /bin/ls -lot "${LS_DIR}" | sed -n '2,21p'
}

# Additional PATH components
export PATH="${PATH}:${HOME}/bin"

# Change the prompt to include the current working directory.
export PS1="\w > "

export DEBUG=/usr/bin/gdb
export EDITOR=/usr/bin/vim

export CC='/usr/bin/gcc -march=pentium3 -msse -pipe'
export CXX='/usr/bin/g++ -march=pentium3 -msse -pipe'

alias switchoff='sudo /sbin/shutdown -h now; exit'

# Make a file "old" so that recdld above doesn't normally show it.
alias mkold='touch -t 200801010000'

alias ff='LD_LIBRARY_PATH=/usr/local/ffmpeg/lib /usr/local/ffmpeg/bin/ffplay'
alias xine='LD_LIBRARY_PATH=/usr/local/xine/lib /usr/local/xine/bin/xine'
alias mu='/usr/local/mupdf/bin/mupdf -r 96'
