# Bash customizations.
# $HOME/.bashrc is a symbolic-link to this file.

# Additional PATH components
export PATH=$PATH:$HOME/bin

# Change our prompt to include the current working directory.
export PS1="\w > "

export DEBUG=/usr/bin/gdb
export EDITOR=/usr/bin/vim

export CC='/usr/bin/gcc -march=pentium3 -msse -pipe'
export CXX='/usr/bin/g++ -march=pentium3 -msse -pipe'

set -o vi

alias switchoff='sudo /sbin/shutdown -h now; exit'
alias recdld='ls -lot | head -20'
alias mkold='touch -t 200801010000'
alias ff='LD_LIBRARY_PATH=/usr/local/ffmpeg/lib /usr/local/ffmpeg/bin/ffplay'
alias xine='LD_LIBRARY_PATH=/usr/local/xine/lib /usr/local/xine/bin/xine'
alias mu='/usr/local/mupdf/bin/mupdf -r 96'
# alias soffice='/opt/OpenOffice/opt/openoffice.org3/program/soffice'
