" Configuration for Vim 7.x or better.
" $HOME/.vimrc is a symbolic-link to this file.

" Force Vim to reload after setting runtimepath.
filetype off
filetype plugin indent off

" Add Go plug-ins for Vim from $GOROOT/misc/vim.
set runtimepath+=/usr/local/go/misc/vim

" Run gofmt on Go source-code when it is saved.
let g:gofmt_command = '/usr/local/go/bin/gofmt -tabs=false -tabwidth=2'
autocmd FileType go autocmd BufWritePre <buffer> Fmt

syntax enable

set nocompatible
set nobackup
set mouse=
set shiftwidth=2
set tabstop=8
set autoindent
set copyindent
set nowarn
set noerrorbells
set visualbell t_vb=
set showmatch
set nohlsearch
set ruler

" Set to 'light'/'dark' for lighter/darker terminal-backgrounds respectively.
set background=dark

" Solarized (http://ethanschoonover.com/solarized) color-scheme.
let g:solarized_termcolors=256
let g:solarized_menu=0
colorscheme solarized

" An alternative color-scheme that goes well with an amber-on-black terminal.
" colorscheme desert

autocmd BufRead,BufNewFile *.htm4 setfiletype html

" Create $HOME/.vim/indent/html.vim with 'let b:did_indent = 1' to disable
" auto-indenting for HTML-type files.

" In source-code files, we do not want TAB characters.
autocmd BufNewFile,BufReadPre *.c setlocal expandtab
autocmd BufNewFile,BufReadPre *.cc setlocal expandtab
autocmd BufNewFile,BufReadPre *.cpp setlocal expandtab
autocmd BufNewFile,BufReadPre *.go setlocal expandtab
autocmd BufNewFile,BufReadPre *.h setlocal expandtab
autocmd BufNewFile,BufReadPre *.hh setlocal expandtab
autocmd BufNewFile,BufReadPre *.hpp setlocal expandtab
autocmd BufNewFile,BufReadPre *.html setlocal expandtab
autocmd BufNewFile,BufReadPre *.htm4 setlocal expandtab
autocmd BufNewFile,BufReadPre *.java setlocal expandtab
autocmd BufNewFile,BufReadPre *.py setlocal expandtab
autocmd BufNewFile,BufReadPre *.sql setlocal expandtab
autocmd BufNewFile,BufReadPre *.xml setlocal expandtab
autocmd BufNewFile,BufReadPre *.y setlocal expandtab

" If you really want to insert a TAB character, press Ctrl+V and then TAB.
inoremap <Tab> <C-V><Tab>

" Force Vim to show 256 colors with mrxvt, if needed.
" (Check with ':echo &t_Co' - should output '256' instead of '8'.)
" mrxvrt must have been configured with --enable-256colors and mrxvt.terminfo
" should have been installed using 'sudo tic mrxvt.terminfo'.
"
" autocmd VimEnter *
"   \ if &term == 'rxvt'	|
"   \   set t_Co=256	|
"   \ endif

" Keep this as the last line.
filetype plugin indent on
