# Bash customizations.
# ${HOME}/.bashrc is a symbolic-link to this file.

set -o vi

# Speed things up a little.
export LC_ALL=C
export LANG=C

# Show the 20 most "recently-downloaded" files in the given directory.
recdld() {
  LS_DIR=${1-$PWD}
  /bin/ls --color=always -lota "${LS_DIR}" | sed -n '2,21p'
}

# Additional PATH components.
if [[ ! "${PATH}" =~ ".*${HOME}/bin.*" ]]
then
  export PATH="${PATH}:${HOME}/bin"
fi

# Change the prompt to include the current working directory.
export PS1="\w > "

export DEBUG=/usr/bin/gdb
export EDITOR='/usr/bin/vim -X'

export CC='/usr/bin/gcc -march=pentium3 -msse -pipe'
export CXX='/usr/bin/g++ -march=pentium3 -msse -pipe'

if [[ "${TERM}" != "linux" ]]
then
    eval `/usr/bin/dircolors ${HOME}/Misc/rcfiles/solarized_dircolors`
fi
alias ls='/bin/ls ${LS_OPTIONS}'

alias switchoff='sudo /sbin/shutdown -h now; exit'

# Make a file "old" so that recdld above doesn't normally show it.
alias mkold='touch -t 200801010000'

alias git="${HOME}/Misc/bin/git"
alias ff='LD_LIBRARY_PATH=/usr/local/ffmpeg/lib /usr/local/ffmpeg/bin/ffplay'
alias xine='LD_LIBRARY_PATH=/usr/local/xine/lib:/usr/local/ffmpeg/lib /usr/local/xine/bin/xine'
alias mu='/usr/local/mupdf/bin/mupdf-x11'

# Setup for Java programs.
export JAVA_HOME="/usr/local/jdk"
alias java="${JAVA_HOME}/bin/java"
alias javac="${JAVA_HOME}/bin/javac"
alias ant="/usr/local/ant/bin/ant"

# Setup for Go programs.
alias go='/usr/local/go/bin/go'
alias gofmt='/usr/local/go/bin/gofmt'
export GOPATH="${HOME}/Go"
