# Bash customizations.
# ${HOME}/.bashrc is a symbolic-link to this file.

set -o vi

# Speed things up a little.
export LC_ALL=C
export LANG=C

# Reduce shell-amnesia.
export HISTCONTROL="ignoredups:ignorespace"
export HISTSIZE=1024
export HISTFILESIZE=8192

# Show the 20 most "recently-downloaded" files in the given directory.
recdld() {
  local LS_DIR="${1-$PWD}"
  /bin/ls --color=always -lota "${LS_DIR}" | /usr/bin/sed -n '2,21p'
  /bin/echo -n '[m'  # ANSI escape-sequence to reset the terminal-colors.
}

# Additional PATH components.
if [[ ! "${PATH}" =~ ".*${HOME}/bin.*" ]]
then
  export PATH="${PATH}:${HOME}/bin"
fi

# Change the prompt to include the current working directory.
export PS1="\w > "

export DEBUG='/usr/bin/gdb'
export EDITOR='/usr/bin/vim -X'
# Update MANPATH to include man-pages usually installed with --prefix=/usr
export MANPATH='/usr/man:/usr/share/man'
# Ensure that "man foo" correctly displays pages containing escape-sequences.
export MANPAGER='/usr/bin/less -isr'

export CC='/usr/bin/gcc -march=pentium3 -msse -pipe'
export CXX='/usr/bin/g++ -march=pentium3 -msse -pipe'

if [[ "${TERM}" != "linux" ]]
then
    eval `/usr/bin/dircolors ${HOME}/Misc/rcfiles/solarized_dircolors`
fi
alias ls='/bin/ls --color=auto'
alias grep='/bin/grep --color=auto'

alias switchoff='sudo /sbin/shutdown -h now; exit'

# Make a file "old" so that recdld above doesn't normally show it.
alias mkold='touch -t 200801010000'

alias git="${HOME}/Misc/bin/git"
alias ff='LD_LIBRARY_PATH=/opt/mm/lib /opt/mm/bin/ffplay'
alias xine='LD_LIBRARY_PATH=/opt/mm/lib /opt/mm/bin/xine'
alias mu='/usr/local/mupdf/bin/mupdf-x11'

# Setup for Java programs.
export JAVA_HOME="/usr/local/jdk"
alias java="${JAVA_HOME}/bin/java"
alias javac="${JAVA_HOME}/bin/javac"
alias ant="/usr/local/ant/bin/ant"

# Set-up for Go programs.
#
# NOTE: Get "cacert.pem" from https://curl.haxx.se/docs/caextract.html and set
# SSL_CERT_FILE="/extra2/cacert.pem" PATH="${PATH}:${HOME}/Misc/bin" before
# invoking "go get -u -v".
alias go='/opt/go/bin/go'
alias gofmt='/opt/go/bin/gofmt'
# vim-go has become too bloated - run gofmt manually when needed.
alias gfall='find . -name *.go -exec /opt/go/bin/gofmt -l -w \{\} \;'
export GOPATH="/extra2/Go"
