" Configuration for Vim 8.x or better.
" $HOME/.vimrc is a symbolic-link to this file.

" Force Vim to reload after setting runtimepath.
filetype off
filetype plugin indent off

" Customize indentation of Python code (see ':help ft-python-indent').
let g:pyindent_open_paren = '&sw'
let g:pyindent_nested_paren = '&sw'
let g:pyindent_continue = '&sw'

syntax enable

set nocompatible
set nobackup
set tabstop=8 shiftwidth=4
set autoindent smartindent cindent copyindent
" Customize cindent (see help-text for cinoptions-values).
set cinoptions=>4,g2,h2,+2,(2,u2,:2,=2
set backspace=indent
set nowarn noerrorbells visualbell t_vb=
set showmatch
set ignorecase nohlsearch
" Hide buffers instead of unloading them when they are abandoned.
set hidden
set mouse=

" Disable relative line-numbers (too slow).
set nonumber norelativenumber

" Show right-justified current & total lines, current column, and if-modified.
set showmode ruler
set rulerformat=%=%1.4l/%1.4L,\ %1.3c\ %m

" Fix ESC-latency (https://www.johnhawthorn.com/2012/09/vi-escape-delays/).
set timeout ttimeout timeoutlen=1024 ttimeoutlen=32

" PaperColor (https://github.com/NLKNguyen/papercolor-theme).
set background=light
let g:PaperColor_Theme_Options = {
  \   'theme': {
  \     'default.light': {
  \       'allow_bold': 1,
  \       'transparent_background': 0,
  \       'override' : {
  \         'linenumber_fg' : ['', '0'],
  \         'linenumber_bg' : ['', '15'],
  \       }
  \     }
  \   }
  \ }
colorscheme PaperColor
" Fix the display of error-messages with PaperColor (see
" https://github.com/NLKNguyen/papercolor-theme/issues/118).
highlight ErrorMsg ctermfg=0 ctermbg=1
" Make warning-messages pop out with a yellow background.
highlight WarningMsg ctermfg=7 ctermbg=226

autocmd BufRead,BufNewFile *.htm4 setfiletype html

" Create $HOME/.vim/indent/html.vim with 'let b:did_indent = 1' to disable
" auto-indenting for HTML-type files.

" In most source-code files, we do not want TAB characters. We also want to
" insert shiftwidth() spaces on pressing TAB. If we really want to insert a TAB
" character, we press Ctrl+V and then TAB.
autocmd BufNewFile,BufReadPre *.c setlocal expandtab softtabstop=-1
autocmd BufNewFile,BufReadPre *.h setlocal expandtab softtabstop=-1
autocmd BufNewFile,BufReadPre *.cc setlocal expandtab softtabstop=-1
autocmd BufNewFile,BufReadPre *.hh setlocal expandtab softtabstop=-1
autocmd BufNewFile,BufReadPre *.cpp setlocal expandtab softtabstop=-1
autocmd BufNewFile,BufReadPre *.hpp setlocal expandtab softtabstop=-1
autocmd BufNewFile,BufReadPre *.html setlocal expandtab softtabstop=-1
autocmd BufNewFile,BufReadPre *.htm4 setlocal expandtab softtabstop=-1
autocmd BufNewFile,BufReadPre *.xml setlocal expandtab softtabstop=-1
autocmd BufNewFile,BufReadPre *.sh setlocal expandtab softtabstop=-1
autocmd BufNewFile,BufReadPre *.py setlocal expandtab softtabstop=-1
autocmd BufNewFile,BufReadPre *.java setlocal expandtab softtabstop=-1
autocmd BufNewFile,BufReadPre *.hs setlocal expandtab softtabstop=-1
autocmd BufNewFile,BufReadPre *.sql setlocal expandtab softtabstop=-1
autocmd BufNewFile,BufReadPre *.y setlocal expandtab softtabstop=-1
" Go is a special snowflake that needs TABs - make it appear less gross.
autocmd BufNewFile,BufReadPre *.go setlocal noexpandtab tabstop=4

" Keep this as the last line.
filetype plugin indent on
