" Configuration for Vim 7.x or better.
" $HOME/.vimrc is a symbolic-link to this file.

" Force Vim to reload after setting runtimepath.
filetype off
filetype plugin indent off

" Add Go plug-ins for Vim.
" set runtimepath+=/extra/go-vim

" Run gofmt on Go source-code when it is saved.
" let g:gofmt_command = '/usr/local/go/bin/gofmt'
" autocmd FileType go autocmd BufWritePre <buffer> Fmt

syntax enable

set nocompatible
set nobackup
set mouse=
set shiftwidth=4
set tabstop=8
set autoindent
set copyindent
" Customize cindent (see help-text for cinoptions-values).
set cinoptions=>4,g2,h2,+2,(2,u2,:2,=2
set nowarn
set noerrorbells
set visualbell t_vb=
set showmatch
set nohlsearch
set ruler

" Set to 'light'/'dark' for lighter/darker terminal-backgrounds respectively.
set background=dark

" Solarized (http://ethanschoonover.com/solarized) color-scheme.
let g:solarized_termcolors=256
let g:solarized_menu=0
colorscheme solarized

" An alternative color-scheme that goes well with an amber-on-black terminal.
" colorscheme desert

autocmd BufRead,BufNewFile *.htm4 setfiletype html

" Create $HOME/.vim/indent/html.vim with 'let b:did_indent = 1' to disable
" auto-indenting for HTML-type files.

" In most source-code files, we do not want TAB characters. We also want to
" insert shiftwidth() spaces on pressing TAB. If we really want to insert a TAB
" character, we press Ctrl+V and then TAB.
autocmd BufNewFile,BufReadPre *.c setlocal expandtab softtabstop=-1
autocmd BufNewFile,BufReadPre *.cc setlocal expandtab softtabstop=-1
autocmd BufNewFile,BufReadPre *.cpp setlocal expandtab softtabstop=-1
autocmd BufNewFile,BufReadPre *.h setlocal expandtab softtabstop=-1
autocmd BufNewFile,BufReadPre *.hh setlocal expandtab softtabstop=-1
autocmd BufNewFile,BufReadPre *.hpp setlocal expandtab softtabstop=-1
autocmd BufNewFile,BufReadPre *.hs setlocal expandtab softtabstop=-1
autocmd BufNewFile,BufReadPre *.html setlocal expandtab softtabstop=-1
autocmd BufNewFile,BufReadPre *.htm4 setlocal expandtab softtabstop=-1
autocmd BufNewFile,BufReadPre *.java setlocal expandtab softtabstop=-1
autocmd BufNewFile,BufReadPre *.py setlocal expandtab softtabstop=-1
autocmd BufNewFile,BufReadPre *.sh setlocal expandtab softtabstop=-1
autocmd BufNewFile,BufReadPre *.sql setlocal expandtab softtabstop=-1
autocmd BufNewFile,BufReadPre *.xml setlocal expandtab softtabstop=-1
autocmd BufNewFile,BufReadPre *.y setlocal expandtab softtabstop=-1

" Force Vim to show 256 colors with mrxvt, if needed.
" (Check with ':echo &t_Co' - should output '256' instead of '8'.)
" mrxvrt must have been configured with --enable-256colors and mrxvt.terminfo
" should have been installed using 'sudo tic mrxvt.terminfo'.
"
" autocmd VimEnter *
"   \ if &term == 'rxvt'	|
"   \   set t_Co=256	|
"   \ endif

" Keep this as the last line.
filetype plugin indent on
