#!/usr/bin/env bash

set -o nounset
set -o errexit
set -o pipefail

# See:
#   http://robertmuth.blogspot.com/2012/08/better-bash-scripting-in-15-minutes.html
#   https://news.ycombinator.com/item?id=7595499
# for tips on writing Bash scripts.
